default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: projector_dev

test:
  <<: *default
  database: projector_test

production:
  <<: *default
  database: projector_prod
