default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: scratch_dev

test:
  <<: *default
  database: scratch_test

production:
  <<: *default
  database: scratch_prod
